In [ ]:
import pandas as pd
df=pd.read_csv('newyork.csv')
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,10/19/2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,5/21/2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,7/5/2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,11/19/2018,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [ ]:
df.shape

(48895, 16)

In [ ]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [ ]:
df.drop_duplicates()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,10/19/2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,5/21/2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,7/5/2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,11/19/2018,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [ ]:
df.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
df.dropna(subset=['name','host_name','last_review','reviews_per_month'],inplace=True)

In [ ]:
df.isna().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [ ]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
5,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,Lovely Privet Bedroom with Privet Restroom,83554966,Rusaa,Manhattan,Upper East Side,40.78099,-73.95366,Private room,129,1,1,2019-07-07,1.00,1,147
48790,36427429,No.2 with queen size bed,257683179,H Ai,Queens,Flushing,40.75104,-73.81459,Private room,45,1,1,2019-07-07,1.00,6,339
48799,36438336,Seas The Moment,211644523,Ben,Staten Island,Great Kills,40.54179,-74.14275,Private room,235,1,1,2019-07-07,1.00,1,87
48805,36442252,1B-1B apartment near by Metro,273841667,Blaine,Bronx,Mott Haven,40.80787,-73.92400,Entire home/apt,100,1,2,2019-07-07,2.00,1,40
48852,36455809,"Cozy Private Room in Bushwick, Brooklyn",74162901,Christine,Brooklyn,Bushwick,40.69805,-73.92801,Private room,30,1,1,2019-07-08,1.00,1,1

In [ ]:
df.dtypes

id                                         int64
name                                      object
host_id                                    int64
host_name                                 object
neighbourhood_group                       object
neighbourhood                             object
latitude                                 float64
longitude                                float64
room_type                                 object
price                                      int64
minimum_nights                             int64
number_of_reviews                          int64
last_review                       datetime64[ns]
reviews_per_month                        float64
calculated_host_listings_count             int64
availability_365                           int64
dtype: object

In [ ]:
df.columns=df.columns.str.lower().str.strip()

In [ ]:
df['last_review']=pd.to_datetime(df['last_review'],dayfirst=True)

/tmp/ipython-input-3547740545.py:1: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['last_review']=pd.to_datetime(df['last_review'],dayfirst=True)

In [ ]:
df['name']=df['name'].str.lower().str.strip()
df['host_name']=df['host_name'].str.lower().str.strip()
df['neighbourhood_group']=df['neighbourhood_group'].str.lower().str.strip()
df['neighbourhood']=df['neighbourhood'].str.lower().str.strip()
df['room_type']=df['room_type'].str.lower().str.strip()

In [ ]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,clean & quiet apt home by the park,2787,john,brooklyn,kensington,40.64749,-73.97237,private room,149,1,9,2018-10-19,0.21,6,365
1,2595,skylit midtown castle,2845,jennifer,manhattan,midtown,40.75362,-73.98377,entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,cozy entire floor of brownstone,4869,lisaroxanne,brooklyn,clinton hill,40.68514,-73.95976,entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,entire apt: spacious studio/loft by central park,7192,laura,manhattan,east harlem,40.79851,-73.94399,entire home/apt,80,10,9,2018-11-19,0.10,1,0
5,5099,large cozy 1 br apartment in midtown east,7322,chris,manhattan,murray hill,40.74767,-73.97500,entire home/apt,200,3,74,2019-06-22,0.59,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,lovely privet bedroom with privet restroom,83554966,rusaa,manhattan,upper east side,40.78099,-73.95366,private room,129,1,1,2019-07-07,1.00,1,147
48790,36427429,no.2 with queen size bed,257683179,h ai,queens,flushing,40.75104,-73.81459,private room,45,1,1,2019-07-07,1.00,6,339
48799,36438336,seas the moment,211644523,ben,staten island,great kills,40.54179,-74.14275,private room,235,1,1,2019-07-07,1.00,1,87
48805,36442252,1b-1b apartment near by metro,273841667,blaine,bronx,mott haven,40.80787,-73.92400,entire home/apt,100,1,2,2019-07-07,2.00,1,40
48852,36455809,"cozy private room in bushwick, brooklyn",74162901,christine,brooklyn,bushwick,40.69805,-73.92801,private room,30,1,1,2019-07-08,1.00,1,1

In [ ]:
display(df['neighbourhood_group'].unique())

array(['brooklyn', 'manhattan', 'queens', 'staten island', 'bronx'],
      dtype=object)

In [ ]:
print('Missing values after cleaning:')
display(df.isna().sum())

Missing values after cleaning:

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [ ]:
print('\nData types after cleaning:')
display(df.dtypes)

Data types after cleaning:

id                                         int64
name                                      object
host_id                                    int64
host_name                                 object
neighbourhood_group                       object
neighbourhood                             object
latitude                                 float64
longitude                                float64
room_type                                 object
price                                      int64
minimum_nights                             int64
number_of_reviews                          int64
last_review                       datetime64[ns]
reviews_per_month                        float64
calculated_host_listings_count             int64
availability_365                           int64
dtype: object

In [ ]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,clean & quiet apt home by the park,2787,john,brooklyn,kensington,40.64749,-73.97237,private room,149,1,9,2018-10-19,0.21,6,365
1,2595,skylit midtown castle,2845,jennifer,manhattan,midtown,40.75362,-73.98377,entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,cozy entire floor of brownstone,4869,lisaroxanne,brooklyn,clinton hill,40.68514,-73.95976,entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,entire apt: spacious studio/loft by central park,7192,laura,manhattan,east harlem,40.79851,-73.94399,entire home/apt,80,10,9,2018-11-19,0.10,1,0
5,5099,large cozy 1 br apartment in midtown east,7322,chris,manhattan,murray hill,40.74767,-73.97500,entire home/apt,200,3,74,2019-06-22,0.59,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,lovely privet bedroom with privet restroom,83554966,rusaa,manhattan,upper east side,40.78099,-73.95366,private room,129,1,1,2019-07-07,1.00,1,147
48790,36427429,no.2 with queen size bed,257683179,h ai,queens,flushing,40.75104,-73.81459,private room,45,1,1,2019-07-07,1.00,6,339
48799,36438336,seas the moment,211644523,ben,staten island,great kills,40.54179,-74.14275,private room,235,1,1,2019-07-07,1.00,1,87
48805,36442252,1b-1b apartment near by metro,273841667,blaine,bronx,mott haven,40.80787,-73.92400,entire home/apt,100,1,2,2019-07-07,2.00,1,40
48852,36455809,"cozy private room in bushwick, brooklyn",74162901,christine,brooklyn,bushwick,40.69805,-73.92801,private room,30,1,1,2019-07-08,1.00,1,1

In [ ]:
df['price'].describe()

count    38821.000000
mean       142.332526
std        196.994756
min          0.000000
25%         69.000000
50%        101.000000
75%        170.000000
max      10000.000000
Name: price, dtype: float64

In [ ]:
df['minimum_nights'].describe()

count    38821.000000
mean         5.869220
std         17.389026
min          1.000000
25%          1.000000
50%          2.000000
75%          4.000000
max       1250.000000
Name: minimum_nights, dtype: float64

In [ ]:
df['number_of_reviews'].describe()

count    38821.000000
mean        29.290255
std         48.182900
min          1.000000
25%          3.000000
50%          9.000000
75%         33.000000
max        629.000000
Name: number_of_reviews, dtype: float64

In [ ]:
df.groupby('room_type')['price'].mean()

room_type
entire home/apt    196.315929
private room        83.985272
shared room         63.213948
Name: price, dtype: float64

In [ ]:
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48782,36425863,lovely privet bedroom with privet restroom,83554966,rusaa,manhattan,upper east side,40.78099,-73.95366,private room,129,1,1,2019-07-07,1.0,1,147
48790,36427429,no.2 with queen size bed,257683179,h ai,queens,flushing,40.75104,-73.81459,private room,45,1,1,2019-07-07,1.0,6,339
48799,36438336,seas the moment,211644523,ben,staten island,great kills,40.54179,-74.14275,private room,235,1,1,2019-07-07,1.0,1,87
48805,36442252,1b-1b apartment near by metro,273841667,blaine,bronx,mott haven,40.80787,-73.92400,entire home/apt,100,1,2,2019-07-07,2.0,1,40
48852,36455809,"cozy private room in bushwick, brooklyn",74162901,christine,brooklyn,bushwick,40.69805,-73.92801,private room,30,1,1,2019-07-08,1.0,1,1

In [ ]:
pd.crosstab(df['room_type'], df['number_of_reviews'])

number_of_reviews,1,2,3,4,5,6,7,8,9,10,...,480,488,510,540,543,576,594,597,607,629
room_type,,,,,,,,,,,,,,,,,,,,,
entire home/apt,2550,1787,1349,1121,918,751,671,613,541,439,...,0,1,0,0,0,0,0,0,0,0
private room,2552,1591,1131,830,658,587,482,475,401,344,...,1,0,1,1,1,1,1,1,1,1
shared room,137,86,39,43,39,18,26,39,22,20,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df['high_price']=df['price']!=10000
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,high_price
0,2539,clean & quiet apt home by the park,2787,john,brooklyn,kensington,40.64749,-73.97237,private room,10000,1,9,2018-10-19,0.21,6,365,False
1,2595,skylit midtown castle,2845,jennifer,manhattan,midtown,40.75362,-73.98377,entire home/apt,10000,1,45,2019-05-21,0.38,2,355,False
3,3831,cozy entire floor of brownstone,4869,lisaroxanne,brooklyn,clinton hill,40.68514,-73.95976,entire home/apt,10000,1,270,2019-07-05,4.64,1,194,False
4,5022,entire apt: spacious studio/loft by central park,7192,laura,manhattan,east harlem,40.79851,-73.94399,entire home/apt,10000,10,9,2018-11-19,0.10,1,0,False
5,5099,large cozy 1 br apartment in midtown east,7322,chris,manhattan,murray hill,40.74767,-73.97500,entire home/apt,10000,3,74,2019-06-22,0.59,1,129,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,lovely privet bedroom with privet restroom,83554966,rusaa,manhattan,upper east side,40.78099,-73.95366,private room,10000,1,1,2019-07-07,1.00,1,147,False
48790,36427429,no.2 with queen size bed,257683179,h ai,queens,flushing,40.75104,-73.81459,private room,10000,1,1,2019-07-07,1.00,6,339,False
48799,36438336,seas the moment,211644523,ben,staten island,great kills,40.54179,-74.14275,private room,10000,1,1,2019-07-07,1.00,1,87,False
48805,36442252,1b-1b apartment near by metro,273841667,blaine,bronx,mott haven,40.80787,-73.92400,entire home/apt,10000,1,2,2019-07-07,2.00,1,40,False
48852,36455809,"cozy private room in bushwick, brooklyn",74162901,christine,brooklyn,bushwick,40.69805,-73.92801,private room,10000,1,1,2019-07-08,1.00,1,1,False

In [ ]:
pd.crosstab(df['room_type'],df['high_price'])

high_price        True
room_type
entire home/apt  20321
private room     17654
shared room        846

In [ ]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
count,3.882100e+04,3.882100e+04,38821.000000,38821.000000,38821.000000,38821.000000,38821.000000,38821,38821.000000,38821.000000,38821.000000
mean,1.810081e+07,6.424582e+07,40.728129,-73.951149,142.332526,5.869220,29.290255,2018-10-04 07:23:47.072975872,1.373229,5.166611,114.886299
min,2.539000e+03,2.438000e+03,40.506410,-74.244420,0.000000,1.000000,1.000000,2011-03-28 00:00:00,0.010000,1.000000,0.000000
25%,8.721444e+06,7.029525e+06,40.688640,-73.982460,69.000000,1.000000,3.000000,2018-07-09 00:00:00,0.190000,1.000000,0.000000
50%,1.887286e+07,2.837092e+07,40.721710,-73.954810,101.000000,2.000000,9.000000,2019-05-19 00:00:00,0.720000,1.000000,55.000000
75%,2.756746e+07,1.018905e+08,40.762990,-73.935020,170.000000,4.000000,33.000000,2019-06-23 00:00:00,2.020000,2.000000,229.000000
max,3.645581e+07,2.738417e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,2019-07-08 00:00:00,58.500000,327.000000,365.000000
std,1.069372e+07,7.589752e+07,0.054991,0.046693,196.994756,17.389026,48.182900,NaN,1.680328,26.302954,129.529950

In [ ]:
df['min_nights']=df['minimum_nights']<5

In [ ]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,high_price,min_nights
0,2539,clean & quiet apt home by the park,2787,john,brooklyn,kensington,40.64749,-73.97237,private room,10000,1,9,2018-10-19,0.21,6,365,False,True
1,2595,skylit midtown castle,2845,jennifer,manhattan,midtown,40.75362,-73.98377,entire home/apt,10000,1,45,2019-05-21,0.38,2,355,False,True
3,3831,cozy entire floor of brownstone,4869,lisaroxanne,brooklyn,clinton hill,40.68514,-73.95976,entire home/apt,10000,1,270,2019-07-05,4.64,1,194,False,True
4,5022,entire apt: spacious studio/loft by central park,7192,laura,manhattan,east harlem,40.79851,-73.94399,entire home/apt,10000,10,9,2018-11-19,0.10,1,0,False,False
5,5099,large cozy 1 br apartment in midtown east,7322,chris,manhattan,murray hill,40.74767,-73.97500,entire home/apt,10000,3,74,2019-06-22,0.59,1,129,False,True

In [ ]:
pd.crosstab(df['min_nights'],df['room_type'])

room_type   entire home/apt  private room  shared room
min_nights
False                  5613          3308          133
True                  14708         14346          713

INSIGHT: So,Here so many people was stayed in the rooms at nights are less than 5

In [ ]:
pd.crosstab(df['calculated_host_listings_count'], df['room_type'], normalize='index') * 100

room_type                       entire home/apt  private room  shared room
calculated_host_listings_count
1                                     61.127339     37.759533     1.113129
2                                     38.040646     59.631753     2.327601
3                                     27.265437     69.887731     2.846832
4                                     23.322933     71.450858     5.226209
5                                     24.320652     69.021739     6.657609
6                                     20.588235     67.226891    12.184874
7                                     21.383648     62.893082    15.723270
8                                     26.813880     62.460568    10.725552
9                                     31.016043     57.754011    11.229947
10                                    16.216216     72.972973    10.810811
11                                    29.166667     69.791667     1.041667
12                                    34.285714     56.428571     9.285714
13                                    38.679245     60.377358     0.943396
14                                    71.428571     21.428571     7.142857
15                                    50.000000     50.000000     0.000000
16                                   100.000000      0.000000     0.000000
17                                    26.666667     45.000000    28.333333
18                                     4.166667     91.666667     4.166667
19                                   100.000000      0.000000     0.000000
20                                    72.000000     28.000000     0.000000
21                                   100.000000      0.000000     0.000000
23                                    57.142857     42.857143     0.000000
25                                    76.923077     23.076923     0.000000
26                                    22.727273     77.272727     0.000000
27                                     0.000000    100.000000     0.000000
28                                    43.589744     28.205128    28.205128
29                                   100.000000      0.000000     0.000000
30                                     0.000000    100.000000     0.000000
31                                   100.000000      0.000000     0.000000
32                                     0.000000    100.000000     0.000000
33                                    88.888889     11.111111     0.000000
34                                    44.776119     28.358209    26.865672
37                                     0.000000    100.000000     0.000000
39                                   100.000000      0.000000     0.000000
43                                     0.000000    100.000000     0.000000
47                                     4.347826     95.652174     0.000000
49                                   100.000000      0.000000     0.000000
50                                   100.000000      0.000000     0.000000
52                                   100.000000      0.000000     0.000000
65                                   100.000000      0.000000     0.000000
87                                   100.000000      0.000000     0.000000
91                                   100.000000      0.000000     0.000000
96                                    98.888889      1.111111     0.000000
103                                    3.921569     96.078431     0.000000
121                                  100.000000      0.000000     0.000000
232                                  100.000000      0.000000     0.000000
327                                   96.135266      3.864734     0.000000

In [ ]:
df['minimum_nights'].corr(df['number_of_reviews'])

np.float64(-0.06936621073754379)

In [ ]:
df['year']=df['last_review'].dt.year

In [ ]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,high_price,min_nights,per_of_availability,year
0,2539,clean & quiet apt home by the park,2787,john,brooklyn,kensington,40.64749,-73.97237,private room,10000,1,9,2018-10-19,0.21,6,365,False,True,36500,2018
1,2595,skylit midtown castle,2845,jennifer,manhattan,midtown,40.75362,-73.98377,entire home/apt,10000,1,45,2019-05-21,0.38,2,355,False,True,35500,2019
3,3831,cozy entire floor of brownstone,4869,lisaroxanne,brooklyn,clinton hill,40.68514,-73.95976,entire home/apt,10000,1,270,2019-07-05,4.64,1,194,False,True,19400,2019
4,5022,entire apt: spacious studio/loft by central park,7192,laura,manhattan,east harlem,40.79851,-73.94399,entire home/apt,10000,10,9,2018-11-19,0.10,1,0,False,False,0,2018
5,5099,large cozy 1 br apartment in midtown east,7322,chris,manhattan,murray hill,40.74767,-73.97500,entire home/apt,10000,3,74,2019-06-22,0.59,1,129,False,True,12900,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,lovely privet bedroom with privet restroom,83554966,rusaa,manhattan,upper east side,40.78099,-73.95366,private room,10000,1,1,2019-07-07,1.00,1,147,False,True,14700,2019
48790,36427429,no.2 with queen size bed,257683179,h ai,queens,flushing,40.75104,-73.81459,private room,10000,1,1,2019-07-07,1.00,6,339,False,True,33900,2019
48799,36438336,seas the moment,211644523,ben,staten island,great kills,40.54179,-74.14275,private room,10000,1,1,2019-07-07,1.00,1,87,False,True,8700,2019
48805,36442252,1b-1b apartment near by metro,273841667,blaine,bronx,mott haven,40.80787,-73.92400,entire home/apt,10000,1,2,2019-07-07,2.00,1,40,False,True,4000,2019
48852,36455809,"cozy private room in bushwick, brooklyn",74162901,christine,brooklyn,bushwick,40.69805,-73.92801,private room,10000,1,1,2019-07-08,1.00,1,1,False,True,100,2019

In [ ]:
df['month']=df['last_review'].dt.month

In [ ]:
df['day']=df['last_review'].dt.day

In [ ]:
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,calculated_host_listings_count,availability_365,high_price,min_nights,per_of_availability,year,month,day,month_name,day_name
last_review,,,,,,,,,,,,,,,,,,,,,
2019-07-07,36425863,lovely privet bedroom with privet restroom,83554966,rusaa,manhattan,upper east side,40.78099,-73.95366,private room,10000,...,1,147,False,True,14700,2019,7,7,July,Sunday
2019-07-07,36427429,no.2 with queen size bed,257683179,h ai,queens,flushing,40.75104,-73.81459,private room,10000,...,6,339,False,True,33900,2019,7,7,July,Sunday
2019-07-07,36438336,seas the moment,211644523,ben,staten island,great kills,40.54179,-74.14275,private room,10000,...,1,87,False,True,8700,2019,7,7,July,Sunday
2019-07-07,36442252,1b-1b apartment near by metro,273841667,blaine,bronx,mott haven,40.80787,-73.92400,entire home/apt,10000,...,1,40,False,True,4000,2019,7,7,July,Sunday
2019-07-08,36455809,"cozy private room in bushwick, brooklyn",74162901,christine,brooklyn,bushwick,40.69805,-73.92801,private room,10000,...,1,1,False,True,100,2019,7,8,July,Monday

### Further Insights by Date Components

In [ ]:
# Average Price by Month
print("\nAverage Price by Month:")
display(df.groupby('month_name')['price'].mean().sort_values(ascending=False))

# Average Number of Reviews by Month
print("\nAverage Number of Reviews by Month:")
display(df.groupby('month_name')['number_of_reviews'].mean().sort_values(ascending=False))

# Average Price by Day of the Week
print("\nAverage Price by Day of the Week:")
display(df.groupby('day_name')['price'].mean().sort_values(ascending=False))

# Average Number of Reviews by Day of the Week
print("\nAverage Number of Reviews by Day of the Week:")
display(df.groupby('day_name')['number_of_reviews'].mean().sort_values(ascending=False))

# Group by Year for overall trends
print("\nListings and Reviews by Year:")
display(df.groupby('year').agg(total_listings=('id', 'count'), average_reviews=('number_of_reviews', 'mean')))

Average Price by Month:

month_name
April        10000.0
August       10000.0
December     10000.0
February     10000.0
January      10000.0
July         10000.0
June         10000.0
March        10000.0
May          10000.0
November     10000.0
October      10000.0
September    10000.0
Name: price, dtype: float64

Average Number of Reviews by Month:

month_name
June         46.238996
July         42.701837
May          20.178085
April        14.503556
February     12.301299
March        11.670807
December     11.495760
January      11.130152
November     10.584270
October       9.816828
September     9.278827
August        7.707156
Name: number_of_reviews, dtype: float64

Average Price by Day of the Week:

day_name
Friday       10000.0
Monday       10000.0
Saturday     10000.0
Sunday       10000.0
Thursday     10000.0
Tuesday      10000.0
Wednesday    10000.0
Name: price, dtype: float64

Average Number of Reviews by Day of the Week:

day_name
Thursday     30.425232
Friday       30.314413
Sunday       30.110246
Saturday     29.920790
Monday       29.137599
Wednesday    28.785822
Tuesday      25.768061
Name: number_of_reviews, dtype: float64

Listings and Reviews by Year:

      total_listings  average_reviews
year
2011               7         8.714286
2012              25         7.120000
2013              48         5.041667
2014             199         4.683417
2015            1388         4.128242
2016            2703         5.982612
2017            3203         8.891664
2018            6047        11.949727
2019           25201        40.197730

In [ ]:
import pandas as pd

# Reload the original dataset to restore the 'price' column
df = pd.read_csv('newyork.csv')

# Re-apply cleaning and preprocessing steps
df.dropna(subset=['name', 'host_name', 'last_review', 'reviews_per_month'], inplace=True)
df.columns = df.columns.str.lower().str.strip()
df['last_review'] = pd.to_datetime(df['last_review'], dayfirst=True)

df['name'] = df['name'].str.lower().str.strip()
df['host_name'] = df['host_name'].str.lower().str.strip()
df['neighbourhood_group'] = df['neighbourhood_group'].str.lower().str.strip()
df['neighbourhood'] = df['neighbourhood'].str.lower().str.strip()
df['room_type'] = df['room_type'].str.lower().str.strip()

df['year'] = df['last_review'].dt.year
df['month'] = df['last_review'].dt.month
df['day'] = df['last_review'].dt.day
df['month_name'] = df['last_review'].dt.month_name()
df['day_name'] = df['last_review'].dt.day_name()

# Verify the 'price' column is restored and looks correct
print("Price column description after reloading and cleaning:")
display(df['price'].describe())

print("Re-running price analysis after fixing the data:")
# Average Price by Month
print("\nAverage Price by Month:")
display(df.groupby('month_name')['price'].mean().sort_values(ascending=False))

# Average Price by Day of the Week
print("\nAverage Price by Day of the Week:")
display(df.groupby('day_name')['price'].mean().sort_values(ascending=False))

In [ ]:
df['month_name']=df['last_review'].dt.month_name()

In [ ]:
df['day_name']=df['last_review'].dt.day_name()

In [ ]:
df.groupby('month_name')['minimum_nights'].sum()

month_name
April        16898
August       14308
December     12486
February      6835
January      20662
July         21768
June         55841
March        12250
May          34643
November      9768
October      11403
September    10987
Name: minimum_nights, dtype: int64

In [ ]:
df.groupby('month_name')['minimum_nights'].max()

month_name
April         370
August        365
December      365
February      365
January       999
July          365
June          999
March         365
May           365
November     1250
October       365
September     500
Name: minimum_nights, dtype: int64

In [ ]:
df.groupby('month_name')['minimum_nights'].min()

month_name
April        1
August       1
December     1
February     1
January      1
July         1
June         1
March        1
May          1
November     1
October      1
September    1
Name: minimum_nights, dtype: int64

In [ ]:
df.groupby('month_name')['minimum_nights'].mean()

month_name
April        8.012328
August       8.603728
December     7.058225
February     8.876623
January      7.469993
July         3.668970
June         4.110187
March        9.510870
May          7.370851
November     8.442524
October      7.380583
September    7.157655
Name: minimum_nights, dtype: float64

In this insight we observed that so many people was staying in rooms at nights in the month of march(9.510),where in the july month people are not staying in the rooms at nights (3.668)

In [ ]:
df.groupby('month')['number_of_reviews'].mean()

month
1     11.130152
2     12.301299
3     11.670807
4     14.503556
5     20.178085
6     46.238996
7     42.701837
8      7.707156
9      9.278827
10     9.816828
11    10.584270
12    11.495760
Name: number_of_reviews, dtype: float64

In this insight we observed that june and july are the highest average no of reviews. And august has the lowest average no of reviews (7.7071)

In [ ]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,calculated_host_listings_count,availability_365,high_price,min_nights,per_of_availability,year,month,day,month_name,day_name
0,2539,clean & quiet apt home by the park,2787,john,brooklyn,kensington,40.64749,-73.97237,private room,10000,...,6,365,False,True,36500,2018,10,19,October,Friday
1,2595,skylit midtown castle,2845,jennifer,manhattan,midtown,40.75362,-73.98377,entire home/apt,10000,...,2,355,False,True,35500,2019,5,21,May,Tuesday
3,3831,cozy entire floor of brownstone,4869,lisaroxanne,brooklyn,clinton hill,40.68514,-73.95976,entire home/apt,10000,...,1,194,False,True,19400,2019,7,5,July,Friday
4,5022,entire apt: spacious studio/loft by central park,7192,laura,manhattan,east harlem,40.79851,-73.94399,entire home/apt,10000,...,1,0,False,False,0,2018,11,19,November,Monday
5,5099,large cozy 1 br apartment in midtown east,7322,chris,manhattan,murray hill,40.74767,-73.97500,entire home/apt,10000,...,1,129,False,True,12900,2019,6,22,June,Saturday

In [ ]:
df.set_index('last_review',inplace=True)

In [ ]:
df['name'].resample('ME').sum()

last_review
2011-03-31    sunlit and cozy williamsburg/greenpoint, brooklyn
2011-04-30                   luxurious condo in dubmo with view
2011-05-31                    loft w/ terrace @ box house hotel
2011-06-30                                                    0
2011-07-31                                                    0
                                    ...
2019-03-31    colorful artistic williamsburg aptmanhattan - ...
2019-04-30    williamsburg  - quiet and comfy staysunny and ...
2019-05-31    cozy quiet room 4 dooglers!sunny bklyn jewel  ...
2019-06-30    front room/double bedcool room in hell's kitch...
2019-07-31    chelsea perfectcbg ctybgd helpshaiti rm#1:1-4b...
Freq: ME, Name: name, Length: 101, dtype: object